### PR TITLE
step1: styling animal show page card

### PR DESCRIPTION
**Pull request by Amani-Maklad**
Screenshot 2022-12-03 at 15 52 45

### CODE REVIEW

**Comment by Amani-Maklad** [comment]
https://user-images.githubusercontent.com/96262605/205460273-f7fb662f-39d2-4b1e-952a-1c9d9a9b6f68.mov

**Comment by Amani-Maklad** [comment]
https://user-images.githubusercontent.com/96262605/205461248-eced2f52-0055-49f8-8667-527fa7124383.mov

**Comment by Amani-Maklad** [comment]
https://user-images.githubusercontent.com/96262605/205461849-fb324012-4562-4691-bdf5-8618896b83cd.mov

**Comment by Amani-Maklad** [comment]
https://user-images.githubusercontent.com/96262605/205462081-f1c81432-19f2-4e94-b2b6-27ec6eb7d6a3.mov

**Comment by Amani-Maklad** [comment]
https://user-images.githubusercontent.com/96262605/205469987-98568f2f-5c61-4393-b6f1-20ebad77d2ae.mov

**Review by GGC0des — APPROVED** [review]
Love it @Amani-Maklad really great design ! Thanks a lot

**Pull request merged**
